module.exports = [
	{ unit: '0.25 kg', unit_name: 'kg', measure: 0.25 },
	{ unit: '1 kg', unit_name: 'kg', measure: 1 },
	{ unit: '1 pack', unit_name: 'pack', measure: 1 },
	{ unit: '0.5 kg', unit_name: 'kg', measure: 0.5 },
	{ unit: '0.3 kg', unit_name: 'kg', measure: 0.3 },
	{ unit: '1.6 L', unit_name: 'L', measure: 1.6 },
	{ unit: '0.226 kg', unit_name: 'kg', measure: 0.226 },
	{ unit: '0.48 kg', unit_name: 'kg', measure: 0.48 },
	{ unit: '0.22 kg', unit_name: 'kg', measure: 0.22 },
	{ unit: '1 L', unit_name: 'L', measure: 1 },
	{ unit: '0.5 L', unit_name: 'L', measure: 0.5 },
	{ unit: '1.75 L', unit_name: 'L', measure: 1.75 },
	{ unit: '2 L', unit_name: 'L', measure: 2 },
	{ unit: '0.33 L', unit_name: 'L', measure: 0.33 },
	{ unit: '0.15 kg', unit_name: 'kg', measure: 0.15 },
];
